// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zQuestionSubmissionItem = z.object({
  title: z.string().min(3).max(50),
  content: z.string().min(10).max(1000),
});

export const zSubmittedAnswer = z.object({
  id: z.optional(z.uuid()),
  content: z.optional(z.string()),
});

export const zQuestionListItem = z.object({
  id: z.optional(z.uuid()),
  title: z.optional(z.string()),
  content: z.optional(z.string()),
  submittedAnswers: z.optional(z.union([z.null(), z.array(zSubmittedAnswer)])),
});

export const zGetQuestionsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetQuestionsResponse = z.array(zQuestionListItem);

export const zPostQuestionsData = z.object({
  body: zQuestionSubmissionItem,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});
